class CheckoutPageElements:
    CHECKOUT_PAGE_VIEW = 'xpath://androidx.recyclerview.widget.RecyclerView[@resource-id="blibli.mobile.commerce:id/rv_checkout"]'
    CHECKOUT_PRODUCT_NAME = 'xpath://android.widget.TextView[@resource-id="blibli.mobile.commerce:id/tv_product_name"]'
    CHECKOUT_PRODUCT_VARIANT = 'xpath://android.widget.TextView[@resource-id="blibli.mobile.commerce:id/tv_variant"]'
    CHECKOUT_PAGE_PAY_BUTTON = 'xpath://android.widget.Button[@resource-id="blibli.mobile.commerce:id/btn_pay"]'
    CHECKOUT_PAGE_PRODUCT_QUANTITY = 'xpath://android.widget.TextView[@resource-id="blibli.mobile.commerce:id/tv_quantity"]'
    CHECKOUT_PAGE_NO_PAYMENT_SELECTED = 'xpath://android.widget.TextView[@resource-id="blibli.mobile.commerce:id/tv_empty_label"]'
    CHECKOUT_PAGE_CHOOSE_PAYMENT_BUTTON = 'xpath://android.widget.TextView[@resource-id="blibli.mobile.commerce:id/tv_payment_choose"]'
    CHECKOUT_PAYMENT_PROMO_RADIO_BUTTON = 'xpath:(//android.widget.TextView[@text="Pembayaran sesuai promo"]/following-sibling::android.view.View)[1]'
    CHECKOUT_PAYMENT_METHOD_VIRTUAL_ACCOUNT = 'xpath://android.view.View[contains(@text, "Virtual Account")]'
    CHECKOUT_PAYMENT_METHOD_VIRTUAL_ACCOUNT_BCA = 'xpath://android.view.View[@resource-id="submit-BcaVaH2h"]'
    CHECKOUT_CONTINUE_WITHOUT_PROMO_BTN = 'xpath://android.widget.Button[@resource-id="btn-continue"]'
    ORDER_STATUS_PAGE = 'xpath://android.view.ViewGroup[@resource-id="blibli.mobile.commerce:id/tb_thank_you_page"]'